package com.example.cronosapp.provider

object RecicleProvider {
    val studentList = listOf(
        "Anna V.",
        "Raul T.",
        "Pepe P.",
        "Miguel V.",
        "Luis T.",
        "Pamela C.",
        "Ramiro D.",
        "Angel F.",
        "Mirella C.",
        "Carmen L.",
        "Lorenzo S.",
        "Paul P.",
        "Carla R.",
        "Luz C.",
        "Claudia M.",
        "Diego H.",
        "Mariana G.",
        "Fernando J.",
        "Sofía N.",
        "Javier O.",
        "Anna V.",
        "Raul T.",
        "Pepe P.",
        "Miguel V.",
        "Luis T.",
        "Pamela C.",
        "Ramiro D.",
        "Angel F.",
        "Mirella C.",
        "Carmen L.",
        "Lorenzo S.",
        "Paul P.",
        "Carla R.",
        "Luz C.",
        "Claudia M.",
        "Diego H.",
        "Mariana G.",
        "Fernando J.",
        "Sofía N.",
        "Javier O."
    )
}